### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [yuzu-r/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by yuzu-r** [comment]
Thanks, Ken - I didn't get how much better it could look, but now that I've added the additional meta tag, I can see the difference. Much more mobile friendly.

**Comment by kenmazaika** [comment]
Awesome job!  Looks great.  Keep up the awesome work coding.
